### ISSUE TITLE
What is the minimum requirements to start with angular2

### ISSUE THREAD

**Issue by codestellar** [angular/quickstart#113]
Hi,
Can you please guide me on the minimum requirements to start with angular 2?
Is rx.js, zonejs is a must?
I tried switching to gulp but I am facing issues

**Comment by Foxandxss** [comment]
All angular packages, zone.js, rx and reflect-metadata.

**Comment by codestellar** [comment]
Thanks @Foxandxss

**Comment by m-vignesh** [comment]
What are the System Requirements needed to develop and run Angular Applications effectively.?
RAM & Processor??

https://npme.npmjs.com/docs/up-and-running/requirements.html 
Is 16GB RAM required for Angular??
Or is 4 or 8GB enough??

**Comment by subhajitmajumder90** [comment]
i am working on angular for quite sometime and I realized that in angular development you need memory than processor. If you have I3 processor in gen 5 or high it should be fine. but you must have min 8 gb ram for use it without any hang or lag. some people do angular with 4 gb ram but i do not re-command that because you feel lag when your project grow long.
