### ISSUE TITLE
avoid same rendering (data binding) when opening the app on many navigators !

### ISSUE THREAD

**Issue by AttilaZz** [angular/quickstart#162]
Suppose I want to host that app on a node js server, when many users access that app, will they have the same rendering ? because when I try to open that quick-start project on different navigators I'm having that issue, when typing on input : some text, the other input on the other navigator get the same text in it, thought because we are sending the data binding to node js, should we do it otherwise ?

Please Help !

**Comment by filipesilva** [comment]
The quickstart is served via https://github.com/johnpapa/lite-server, which in turn uses https://github.com/BrowserSync/browser-sync. Browser-Sync is the one keeping your browsers in sync, it is a useful dev feature.

When hosting the application on your server, you would not use `lite-server` because it is a dev-only server. You would use a production server instead and thus not have this issue.

**Comment by AttilaZz** [comment]
Thank's, is there a way to run node js in prod mode with that lite server (a parameter in command line or file configuration) ??

**Comment by filipesilva** [comment]
I'm afraid not. It's a dev only server by nature, there is no production setting.

**Comment by AttilaZz** [comment]
Okey then, so I should not worry about this, I should keep developing my app and and hots in a prod server after

**Comment by filipesilva** [comment]
Absolutely correct :D

**Comment by AttilaZz** [comment]
Thanks a lot and forgive my silly question :p

**Comment by maddela** [comment]
Hello I uploaded sample code of node application of angular 2 quickstart. Instance is not running in Aws server as well as Ibm bluemix. can any one tell whats the issue.

And I want configure angular 2 in html with php or java ..

**Comment by filipesilva** [comment]
@AttilaZz not silly at all, it's a very reasonable concern and I'm glad you asked, because other people might have it as well and find an answer here.

@maddela I can't begin to guess what the issue is, there are many things that could have gone wrong in your deployment. This repository is about the quickstart though and doesn't really propose any specific deployment procedure, so I don't think this repo is the right place to ask.

Perhaps try asking someone very knowledgeable in AWS/IBM Bluemix? They might be able to help you in the transition from a local setup to a deployed setup.
