### ISSUE TITLE
Starting Tests and Application Concurrently

### ISSUE THREAD

**Issue by crehn** [angular/quickstart#193]
> It is unwise and rarely possible to run the application, the unit tests, and the e2e tests at the same time. We recommend that you shut down one before starting another.

Why is it unwise to run application and tests concurrently? When developing my application I'd like to have immediate feedback. I want to see failing tests and I want to see broken layout. I don't want to constantly cancel and restart `npm start` and `npm test` to get this feedback.

And why should it be rarely possible? They start on different ports so what is the problem? 

If there is a problem, it would be nice if the readme explains this shortly. It would be even better if this constraint wasn't there in the first place.

**Comment by theBull** [comment]
My guess is that a large scale angular app would suck up too much resources; it could make the performance of one or more of the processes to run inefficiently and take longer, especially within an org with many unit and e2e tests. If the application runs slowly because you've got a lot of memory allocated to your tests, it could falsely convey that the application itself has a performance issue.

Just my two cents, I could be way off.

**Comment by crehn** [comment]
Maybe you're right. But actually, I don't think so. Most likely you have plenty of other programs running while developing. Browser, IDE, email client, feedreader, ... maybe even some backend services you are also developing. lite-server is just one more. That shouldn't be much of a problem. In other words: If that's the problem, then lite-server would be a performance nightmare anyway (which I don't believe).

**Comment by filipesilva** [comment]
While it is perfectly fine (and encouraged) to run the unit tests in watch mode while coding your app, running the e2e tests as well is overall a bad idea. The answer lies in what you said:

>When developing my application I'd like to have **immediate feedback**.

Unit tests are usually fast because they test the classes etc in isolation. So mostly it's just some bits of code running, albeit the tests might number in the hundreds.

E2E tests, however, are a different beast all together. They work by firing up the browser, interfacing with it via protractor, and running a bunch of interactions as if you were doing them yourself. Meaning it's clicking on buttons, sending keys to input fields, etc on chrome. This is way more computationally intensive, and overall slow, than unit tests.

So while 500 unit tests might take ten seconds, it's not that uncommon to have 100 e2e tests take 20 minutes.

Essentially this means that e2e tests can never give you the immediate feedback you want and need, while unit tests kinda can.
