### ISSUE TITLE
How to run angular 2 application on apache hosting server

### ISSUE THREAD

**Issue by nikvarma** [angular/quickstart#226]
Hi Guys,

I have hosting plan and i want to host my angular 2 application on the hosting server which have apache server.

The hosting server don't have a npm install.

after below command and getting a like the strc

file strc

![image](https://cloud.githubusercontent.com/assets/3116497/18807874/b73f9ab6-8207-11e6-91fe-9d10bc053a7a.png)

![image](https://cloud.githubusercontent.com/assets/3116497/18807875/bc103d66-8207-11e6-917d-f05874569256.png)

ng build --prod

and uploading to my hosting server, when i am accessing the my url

http://www.exmaple.com/ -- it's working properly
http://www.exmaple.com/home -- it's giving a error, the file is no found on the server - 404

but the same thing working on my machine, when i am trying using a cmd
ng serve - command

**Comment by filipesilva** [comment]
Heya @nikvarma, your issue is better suited to the CLI repo at https://github.com/angular/angular-cli since it seems like that's what you're using (this is the quickstart).

That being said, I know the answer to your problem. You need to configure apache to have a fallback to `index.html` when you try to access an address that doesn't exist. 

We don't have a production deploy chapter for Angular 2, but in the meanwhile you can see similar configuration for Angular 1 in https://ngmilk.rocks/2015/03/09/angularjs-html5-mode-or-pretty-urls-on-apache-using-htaccess/ for instructions on how to make an `.htaccess` that allows that.
