### ISSUE TITLE
Error Angulare Core Component - Visual studio community 2015 Update 3 / Getting started Angular 2

### ISSUE THREAD

**Issue by CTotophe** [angular/quickstart#246]
Hi,

I try to understand angular 2. I am getting started the hero tutorial. I downloaded the quickstartzip. 
I create a TypeScript project in VS 2015. I configured NPM but I have a problem with app.component.ts file.
I have an error with Component module. There is not members exported in "/node_modules/@angular/core/index".
I use Angular core 2.0.1

I need your help. Thanks :)

**Comment by CTotophe** [comment]
![pasted2](https://cloud.githubusercontent.com/assets/22611672/19362912/b43e5100-9188-11e6-912e-42ca9fbc3d0f.png)

**Comment by filipesilva** [comment]
@DeborahK could you have a look?

**Comment by wardbell** [comment]
Can you "Show all files" and look for the hidden `node_modules` folder. Do you see the missing file inside `node_modules/@angular/core`? If not, it would seem that VS did not install node modules for you. It should have.  Please make sure that your Visual Studio is configured as described in the cookbook.

I'm going to close this because it's really a problem related to the VS cookbook in angular.io, not this Getting Started repo.  If you can't solve it here, please raise an issue there.
