### ISSUE TITLE
node @type not being found, node_modules excluded

### ISSUE THREAD

**Issue by Tathanen** [angular/quickstart#306]
I'm having an issue where `moduleId: module.id` in a component is throwing a "cannot find name 'module'" error.  It looks like this is handled by the `node` typings.  Looking at my `tsconfig.json`, the `exclude` property with the value of `"node_modules/*"` seems to be to blame.  If I pull that out, the node_modules directory is traversed, and `@types/node` is discovered as it should be.

So.. why is this being excluded?  Presumably because we don't want to traverse ALL of the modules when all we really want is types?  There used to be a `typeRoots` property in `tsconfig.json` that looked like it would maybe add the `@types` directory as an exception to the exclude, but it's been removed for some reason.  I tried adding it back but it didn't seem to provide an exception as I had hoped.

At the moment, removing the node_modules exclude value fixes my issue, but makes compilation take forever.  What's the actual solution here?

**Comment by Tathanen** [comment]
Adding this:

````
/// <reference path="../node_modules/@types/node/index.d.ts" />
````

to the top of my app module fixes my issue, but this is old typescript syntax I feel like I really shouldn't be using.  There should be a `tsconfig.json` way to resolve this, but the "exclude" setting seems to override most of my options there.

**Comment by wardbell** [comment]
Something else is wrong with your setup. You definitely do not ... and should not ... make the changes you've described.

The node type information should be coming from the npm installation of `node.d.ts` which you should see in `node_modules/@types/node` ... and obviously you do have that ^^^

The `exclude` option is present because the see takes pains to exclude compilation any AoT-specific files.

You never want the TS compiler to compile anything in `node_modules`.
The TS compiler normally excludes `node_modules` by default. But once you start excluding _anything_ you have to exclude everything explicitly, including  `node_modules`. Not doing so is why "_compilation take forever. _"

Excluding AoT files isn't necessary in a seed and I'm going to remove it which means I'll be removing the _entire `exclude` clause_. 

I'm compiling just fine. But I'll be that won't work for you because something else is weird in your world.

I'm guessing you some how are compiling with an old version of TypeScript or npm or something in your environment that I can't see.

I can assure you that **this seed works when installed cleanly**. You'll just have to keep looking for what's different in your world. Sorry.

p.s.: Here's what my package versions look like today:
```bash
> npm list --depth=0
angular-quickstart@1.0.0 C:\github\DELETEME
+-- @angular/common@2.2.3
+-- @angular/compiler@2.2.3
+-- @angular/core@2.2.3
+-- @angular/forms@2.2.3
+-- @angular/http@2.2.3
+-- @angular/platform-browser@2.2.3
+-- @angular/platform-browser-dynamic@2.2.3
+-- @angular/router@3.2.3
+-- @types/jasmine@2.5.38
+-- @types/node@6.0.51
+-- @types/selenium-webdriver@2.53.35
+-- angular-in-memory-web-api@0.1.16
+-- canonical-path@0.0.2
+-- concurrently@3.1.0
+-- core-js@2.4.1
+-- http-server@0.9.0
+-- jasmine-core@2.4.1
+-- karma@1.3.0
+-- karma-chrome-launcher@2.0.0
+-- karma-cli@1.0.1
+-- karma-htmlfile-reporter@0.3.4
+-- karma-jasmine@1.0.2
+-- karma-jasmine-html-reporter@0.2.2
+-- lite-server@2.2.2
+-- lodash@4.17.2
+-- protractor@4.0.9
+-- reflect-metadata@0.1.8
+-- rimraf@2.5.4
+-- rxjs@5.0.0-beta.12
+-- systemjs@0.19.40
+-- tslint@3.15.1
+-- typescript@2.0.10
```

**Comment by Tathanen** [comment]
Hm, I'll keep pokin at it then.  I actually started the angular quickstart tutorial last week and then it was updated halfway through, so I'm kind of straddling worlds here.  I updated the various json and config files and I feel like I've got everything up to date, but this is really the first weird issue I'm finding.

A couple things I am doing differently, though:

- I'm using atom-typescript to compile instead of the tsc command-line watch, the IDE assistance is invaluable and I think I was double-building everything before, so I just run lite-server and let atom do what it does
- I've set a custom "outDir" since building all the js and map files in my working app directory was proving to be an indecipherable mess (this is something I'd like to see changed in this repo actually).  Though this isn't ideal, since my template files aren't automatically moved from `app` to `dist` like my typescript output is.  I'll need a more robust build process here in the future, to be sure.

When I try to run tsc on the command line, I actually get a whole separate set of errors, like thirty separate errors in `node_modules/@types/core-js/index.d.ts` complaining mainly about modifiers.  So there may indeed be something weird with my setup that I don't entirely understand.

If nothing here jumps out at you, I suppose it'd be best to just stash my app directory and rebuild the environment from scratch.

**Comment by wardbell** [comment]
I think you had best start over.  Most of use VS Code which makes it easy to hide the generated `.js` and `.js.map` files ... no mess.  Not sure how to do that in your atom editor.

We will likely start having a build directory soon but only after we have tooling to make it easier. You don't want to manually deal with the fact that "_my template files aren't automatically moved from app to dist like my typescript output is_" (same problem with your component CSS files).

Without that tooling, we're keeping our current structure.

I'll bet your problems stem from moving stuff around. Good luck.
