### ISSUE TITLE
Bundling?

### ISSUE THREAD

**Issue by leebenson** [angular/quickstart#370]
I get that this is a minimal build intended for local dev, but there will be a point when users want to deploy something, and there's no built-in 'graduation' if they start building on this repo.

It'd be nice to have an `npm run build` or equivalent to bundle, minify and tree-shake into a single `bundle.js` for convenience, to let users quickly upload something and see it working live.

That's a surprisingly difficult step for an Angular newbie, when the CLI abstracts away the webpack details and many generators are out of date or no longer maintained.

**Comment by magnayn** [comment]
Grumpiness ahead.

Not to mention the nightmare of 'just as I've built something that works with systemjs, the story for 'deploy into live' seems to be angular-cli, which doesn't seem to use systemjs, and requires an utterly different directory layout', and looks like it's much, much slower for refreshing when in development. 

Oh and of course it's permanently in beta.

Or use some 500-line gulp file (what that?) "found on the interwebs".

I liked that ng2 was opinionated. E.g: we're using typescript. You don't have to, but that's what the default is. 

I wish the project(ecosystem) would just pick something and document it (e.g: example repo) rather than assuming everyone fully understands the clown-car engineering that seems to be the JS build chain.

**Comment by Foxandxss** [comment]
No worries my friend, we are making a lot of changes right now in those aspects.

We have a deploy guide and we will update the quickstart as well.

**Comment by leebenson** [comment]
I encountered pretty much everything @magnayn discovered in my first few days of using Angular, and wound up writing my own Webpack config.

It was a giant PITA that took:

-  3 different TypeScript loaders to find one that actually works (hint: `awesome-typescript-loader`)
-  Trawling through SO and issue boards to figure to figure out why I was getting cyclic dependency issues in the build (hint: `/angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/` - yeah, WTF)
-  Separate loaders for routine stuff like `templateUrl` to resolve _actual_ files, and not just throw cryptic console 404s
- Proper handling of HTML and CSS processing/minification (including postcss)
- Swapping out the 90% of starter kits that use Webpack 1, and miss out on tree-shaking of v2 and es6 modules
- Separate builders for universal Angular, so initial page dumps/SSR was possible
- Proper hot reloading -- not full refreshes like with browsersync

I'm a new ng user transitioning from React, so luckily I had some experience with wrestling webpack. For someone that's completely new to this, I have no idea how anyone, anywhere, has actually managed to build anything with ng2 so far. I spent 5 mins on the official docs before submitting a PR for a pretty obvious error. It's a minefield.

I'm still working on it, but I'm gonna finish my webpack config and post it as an alternative to the starter kits currently out there.

The CLI is a great effort, but hiding the set-up behind magic is going to bite people in the ass before too long. Anyone coming from a 'magic' framework like Meteor will know exactly what I'm talking about.

**Comment by leebenson** [comment]
And, I'm sure I speak for others @Foxandxss, I certainly appreciate all efforts to build something like this quickstart guide. My main peev as a new user is lack of 'official' consistency. A user is either faced with going it alone or trusting everything to the CLI. Neither is ideal.

A simple, solid webpack starter that works in browsers - and is **kept up to date** - would be awesome.

I'll post my attempt at that here when it's finished, hopefully in the next couple of days.

**Comment by Foxandxss** [comment]
The webpack guide is getting better and better and it comes with fully development, test and production. Will bring AOT soon.

**Comment by oztek22** [comment]
My angular project is calling more than 100 dependency files. 
Can you add bundle of just dependency files for starter.(one which are called from node_modules).

**Comment by cojack** [comment]
Any progress?

**Comment by HarelM** [comment]
I was hoping this thread will yield some code I can use to bundle.
If anyone has a link to a good post please let me know.
here's the situation I'm struggling with:
I downloaded the quick start project and wanted to bundle it. no code changes.
I'm using gulp and so I added a gulp file:
```js
var gulp = require('gulp');
var Builder = require('systemjs-builder'); 

gulp.task('bundle', function () {
    var builder = new Builder("./", "./systemjs.config.js");
    builder.bundle("app/*.js", "./app.bundled.js");
});
```
This fails with the following error message:
```
application.module.js document is not defined] originalErr: [ReferenceError: document is not defined] }
```
apparently this is due to the following line in `systemjs.config`:
`loader: "systemjs-angular-loader.js"`. Commenting out this line fixes the above error and a file is created.
Does this mean the quickstart example should be altered? I'm new to bundling etc, am I doing something wrong? should I not be using systemjs although the quickstart references it (which I assume is best known method according to angular team...?)

**Comment by Foxandxss** [comment]
The official recommendation to build and bundle projects is the CLI.

This project was created to be used with the documentation, not to create projects really.

**Comment by HarelM** [comment]
Thanks for the quick response, however, I'm using VS to build my backend and I'm used to it, so I'm using it for angular and typescript development as well, I hope I can make VS use angular-cli, this is not an easy task I think.

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
