### ISSUE TITLE
Best way to build and deploy?

### ISSUE THREAD

**Issue by neolwc** [angular/quickstart#49]
Is there a best/recommended way to build and deploy the projects based on this quickstart?

**Comment by Foxandxss** [comment]
Hello Wenchen, thanks for your issue.

This repository is not meant to be used on real projects, it is just a mirror of the tutorial at angular.io.

So the recommendation here is not to use this repository to build your own projects.

Cheers.

**Comment by Foxandxss** [comment]
Yes, we plan on covering tooling in the tutorials, but I don't know how soon.

**Comment by neolwc** [comment]
That would be wonderful for beginners like me! Thank you!

**Comment by wardbell** [comment]
To be clear, the point of this repo is to make it easy for you to duplicate the end state of  the documented quick start.

From there you can venture in new directions the same way the documented samples do. For they all begin on this quick start foundation.

Because we update it for each release, you can be sure that it always works.

**Comment by wardbell** [comment]
Closing because the request is out of scope for this repo and we have no plans to pursue this request here.
