### ISSUE TITLE
npm fails on npm start 

### ISSUE THREAD

**Issue by sjoerdbr** [angular/quickstart#504]
Hey everyone, U try to start the quickstart tutorial. I'm currently in the last part (HTTP) but I'm not able to run the project. This happened earlier but then I just removed everything and started again. But if this seems to be a recurring problem I think it might be a bug. (or perhaps I'm doing something wrong.

node -v:
v6.11.3

npm -v: 3.10.10

NPM debug log:
[npm-debug.log](https://github.com/angular/quickstart/files/1347424/npm-debug.log)

Hopefully anyone can help me.

Thank you in advance!

**Comment by mrdjar** [comment]
Hello,
I am also having an issue installing quickstart.  Here are the errors with the log file:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/

[npm-debug.log](https://github.com/angular/quickstart/files/1400208/npm-debug.log)

**Comment by sboden** [comment]
@mrdjar ... I also got your error. It simply means `typescript` isn't installed (`tsc` is typescript). So if you do `npm install typescript -g ` that should already fix your error.

But then you will get others. In the current state the rxjs version in use by the tutorial won't work (because of an error in the "lift" function), if you change in `package.json` rxjs and typescript to "rxjs": "^5.4.2" and "typescript": "^2.3.4" and do `npm install` again, then that part should also work.

But then you get some other errors, which  I'm not yet through yet.

**Comment by code-devp** [comment]
I'm having the same error

**Comment by Foxandxss** [comment]
This repository is now deprecated. The Angular Quickstart project was a nice starting point for creating Angular applications. Now we recommend using the [Angular CLI](https://github.com/angular/angular-cli) to create new Angular projects.

Starting from 1 November 2017, all the Angular documentation, at [angular.io](https://angular.io), is based on the Angular CLI.

Let's [get started](https://angular.io/guide/quickstart)
