### ISSUE TITLE
Error when running `npm install`

### ISSUE THREAD

**Issue by otrenav** [angular/quickstart#85]
I just cloned the repo and when I run `npm install`, I get:

```
npm http 404 https://registry.npmjs.org/angular/core/2.0.0-rc.0
npm ERR! 404 'angular' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
```

Should I change something? Thanks!

**Comment by wardbell** [comment]
Should work. Just tried it for RC1.  What version of node and npm are you using? 

That link seems weird. Where did that come from?  I don't see the leading `@` in front of Angular

You can download that package specifically with https://registry.npmjs.org/@angular/common/-/common-2.0.0-rc.0.tgz

Closing because can't repro

**Comment by otrenav** [comment]
I tried it again, and it did work. Not sure how I broke it before. Thanks.
